### ISSUE TITLE
Can not build on OS X, epoll not supported

### ISSUE THREAD

**Issue by IngwiePhoenix** [williame/hellepoll#2]
Hey.

I just wanted to report that epoll is not supported under OS X:
http://stackoverflow.com/questions/13856413/does-os-x-not-support-epoll-function

I figured when I got the compiler error, about the file not being found

```
 $ make
g++ -g3 -Wall  -O0   -c helloworld.cpp -MD -MF helloworld.dep -o helloworld.opp
In file included from helloworld.cpp:5:
In file included from ./listener.hpp:7:
./task.hpp:13:10: fatal error: 'sys/epoll.h' file not found
#include <sys/epoll.h>
         ^
1 error generated.
make: *** [helloworld.opp] Error 1
```

Kind regards :3

**Comment by williame** [comment]
This is correct.  Epoll is a Linux-only API.  Hellepoll uses epoll, which is in it's name.

You could port it to use kqueue, which OSX does support.

**Comment by luckypoem** [comment]
@williame , how to "port it to use kqueue"?
